### ISSUE TITLE
grunt-liquid

### ISSUE THREAD

**Issue by HansUXdev** [ianpatrickhines/nationbuilder-foundation#1]
Hey this looks pretty cool. 
I'm not used to liquid but i've worked with assemble. That said I was wondering how would I develop locally on windows? Have you checked out grunt-liquid? 

https://www.npmjs.com/package/grunt-liquid

**Comment by ianpatrickhines** [comment]
I haven't, but you can't develop NationBuilder themes locally on Windows. They can only be synced to the server using the company's Theme Sync app, which is Mac only.

**Comment by HansUXdev** [comment]
Ok cool, I figured it out (or a version of it).
