### ISSUE TITLE
How to Create a "New, Blank Theme"?

### ISSUE THREAD

**Issue by tsmith0511** [ianpatrickhines/nationbuilder-foundation#2]
Hi there!

I've been waiting for something like this ever since I started working with Nationbuilder! 

However, I haven't been successful in implementing this theme into a "new, blank theme". What do you mean by this? When you create a new, custom theme, you either have to clone the current theme, which you advised not to do, or start with a Bootstrap framework. So, I started with a Bootstrap framework, deleted all those files, uploaded your nationbuilder-foundation files, used Theme Sync to sync to that theme, but the Bootstrap files keep appearing in my local file. As soon as I start editing my _settings.scss file, the site breaks. 

Can you please clarify? I would LOVE to use this.

Thanks!

**Comment by ianpatrickhines** [comment]
Hello!

Those instructions were written months ago, before NationBuilder released their Bootstrap Framework. I guess they’re outdated at this point. 

At this stage, my honest recommendation is to use NationBuilder’s Bootstrap Framework instead. I’ve been doing so myself for my last ~10 projects, and I’m thrilled with the results. It basically addresses every theme shortcoming that NationBuilder Foundation was designed to overcome, and is easier to setup and maintain. 

The only meaningful difference between their Bootstrap Framework and NationBuilder Foundation is which front-end framework they use, but Bootstrap and Foundation are substantially similar in most respects anyway.

I’m going to updated NationBuilder Foundation’s README to indicate that it’s no longer being actively supported and recommend that folks use Bootstrap, instead. Thanks for bringing it to my attention.
