### ISSUE TITLE
Maintaining / Collaborating for Foundation 6

### ISSUE THREAD

**Issue by HansUXdev** [ianpatrickhines/nationbuilder-foundation#3]
I know you recommend using the new bootstrap default theme, but are you considering maintaining or updating this theme?

I ask because foundation 6 will be released soon (private alpha end of this month) and I plan on building a new theme based on it.

**Comment by ianpatrickhines** [comment]
I’m not planning on maintaining or updating this theme. I haven’t used it in several months, and have instead been exclusively using NationBuilder’s officially supported Bootstrap 3 theme. I expect they’ll release a Bootstrap 4 theme, as well, once that hits public release.

If you’d like to clone this repo, update it, and continue maintaining it, I’d be happy to link to your newer version in the README.

**Comment by HansUXdev** [comment]
Cool. I've already cloned it (I believe) it but I may not started to maintaining yet because I'm working on integrating theme-sync with a grunt work flow to deal with some of the sort comings of nation-builder and theme-sync in general. 
(check it out here if you are curious: https://github.com/HansUXdev/Codedrops-NationBuild-Theme)

Also, wouldn't mind having your opinion on it since you are one of the few people who works on nationbuilder projects and publishes their work.
